// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BubbleSort(arg1:Array<number>):Promise<Array<number>>;

export function GenerateSlice(arg1:number):Promise<Array<number>>;

export function InsertionSort(arg1:Array<number>):Promise<Array<number>>;

export function QuickSort(arg1:Array<number>):Promise<Array<number>>;

export function ShellSort(arg1:Array<number>):Promise<Array<number>>;
