// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BinaryInsertionSort(arg1:Array<number>):Promise<Array<number>>;

export function BubbleSort(arg1:Array<number>):Promise<Array<number>>;

export function GenerateSlice(arg1:number):Promise<Array<number>>;

export function Greet(arg1:string):Promise<string>;

export function Insertion_sort(arg1:Array<number>):Promise<Array<number>>;

export function ParallelBatcherSort(arg1:Array<number>):Promise<Array<number>>;

export function QuickSort(arg1:Array<number>):Promise<Array<number>>;

export function Shell_sort(arg1:Array<number>):Promise<Array<number>>;

export function TournamentSort(arg1:Array<number>):Promise<Array<number>>;
