// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BinaryInsertionSort(arg1) {
  return window['go']['main']['App']['BinaryInsertionSort'](arg1);
}

export function BubbleSort(arg1) {
  return window['go']['main']['App']['BubbleSort'](arg1);
}

export function GenerateSlice(arg1) {
  return window['go']['main']['App']['GenerateSlice'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ParallelBatcherSort(arg1) {
  return window['go']['main']['App']['ParallelBatcherSort'](arg1);
}

export function QuickSort(arg1) {
  return window['go']['main']['App']['QuickSort'](arg1);
}

export function TournamentSort(arg1) {
  return window['go']['main']['App']['TournamentSort'](arg1);
}
