// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BubbleSort(arg1) {
  return window['go']['main']['App']['BubbleSort'](arg1);
}

export function GenerateSlice(arg1) {
  return window['go']['main']['App']['GenerateSlice'](arg1);
}

export function InsertionSort(arg1) {
  return window['go']['main']['App']['InsertionSort'](arg1);
}

export function QuickSort(arg1) {
  return window['go']['main']['App']['QuickSort'](arg1);
}

export function ShellSort(arg1) {
  return window['go']['main']['App']['ShellSort'](arg1);
}
